resources:
- name: tasks-git
  type: git
  source:
    uri: https://github.com/kdvolder/deploy-start-spring-io.git
- name: weekly
  type: time
  check_every: 24h
  source:
    interval: 160h
- name: start-git
  type: git
  source:
    uri: https://github.com/spring-io/start.spring.io.git
- name: cf
  type: cf
  source:
    api: ((cf_api_url))
    organization: FrameworksAndRuntimes
    space: sts-development
    username: ((cf_user))
    password: ((cf_password))
jobs:
- name: build-and-push
  plan:
  - in_parallel:
    - get: weekly
      trigger: true
    - get: start-git
      trigger: true
    - get: tasks-git
  - task: build
    file: tasks-git/tasks/build.yml
  - put: cf
    params:
      manifest: tasks-git/manifest.yml
      path: output/start-site-exec.jar
      show_app_log: true
