platform: linux
image_resource:
  type: registry-image
  source:
    repository: openjdk
    tag: 8-jdk
inputs:
- name: start-git
- name: tasks-git
outputs:
- name: output
run:
  path: tasks-git/tasks/build.sh